spring.application.name=practica

#guarda bd en memodia
spring.datasource.url=jdbc:h2:mem:test
#para guardar bd en disco
#spring.datasource.url=jdbc:h2:./db/database;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.username=sa
spring.datasource.password=
#crea y borra las tablas al salir
spring.jpa.hibernate.ddl-auto=create-drop
#muestras las sentencias en el log
spring.jpa.show-sql=true
