spring.application.name=fundamentos-spring-jpa-todoapp-rest

# url de jdbc para la conexion
spring.datasource.url=jdbc:postgresql://localhost:5432/todoapp_db

# datos de acceso
spring.datasource.username=admin
spring.datasource.password=123

spring.jpa.hibernate.ddl-auto=create
spring.sql.init.model=always
spring.jpa.properties.hibernate.hbm2ddl.import_file_sql_extractor=org.hibernate